language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.3"
  - travis_retry composer i --prefer-dist --no-interaction --dev -o

script:
  - whoami
